"""add_instance_type_to_pod

Revision ID: c3d824a79142
Revises: 98fd9f9cd53b
Create Date: 2025-08-15 01:47:36.210295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d824a79142'
down_revision: Union[str, Sequence[str], None] = '98fd9f9cd53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('instance_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod', 'instance_type')
    # ### end Alembic commands ###
